# Site
name: 'chipmastervn'
description: 'Truyền cảm hứng, dẫn dắt tương lai: Kiến tạo tri thức về kĩ thuật và công nghệ!'
logo: assets/images/logo/logo-home.webp
favicon: 'assets/images/favicon.png'
baseurl: ""
disqus: 'demowebsite'
email: 'chipmastervn@gmail.com'
mailchimp-list: 'https://formspree.io/f/xqakpgyn'

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    chipmaster:
      name:           chipmastervn
      site:           https://www.facebook.com/chipmastervn
      avatar:         assets/images/avatar1.webp
      bio:            "Truyền cảm hứng, dẫn dắt tương lai: Kiến tạo tri thức về kĩ thuật và công nghệ!"
      email:          wowthemesnet@gmail.com
      instagram:        https://www.instagram.com/chipmastervn/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: chipmastervn
      avatar: assets/images/avatar1.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 8



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]